[build]
  publish = "public"
  command = "hugo --gc --minify -b $URL"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --buildDrafts -b $DEPLOY_PRIME_URL"
