[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.72.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildDrafts --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[redirects]]
  from = "https://aerialls.netlify.app"
  to = "https://www.aerialls.io"
  status = 301
  force = true

[[redirects]]
  from = "https://julienbrochet.fr"
  to = "https://www.aerialls.io"
  status = 301
  force = true

[[redirects]]
  from = "https://www.julienbrochet.fr"
  to = "https://www.aerialls.io"
  status = 301
  force = true
